### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by jbleyel** [Belfagor2005/mmPicons#1]
Hi,
please check this -> 
https://github.com/jbleyel/mmPicons/commit/14da4ba8d4c218f23ad56148032877637f6458aa

Hints : 
MMarkBlack and MMarkTrasp are 100% equal and can be replaced by one class.
MMarkMov is also 99% similar to MMarkBlack and MMarkTrasp.

MMarkFolderBlk, MMarkFolderTrs and MMarkMov can be a child class from a new class with only a few lines of code

MMarkFolderSkinZeta and MMarkFolderSkinOZeta can be a child class from a new class with only a few lines of code

checkMyFile is a problem because this will download the full file if exists.

**Comment by Belfagor2005** [comment]
I'm not very good in english and google doesn't help much, if you have changes to propose go ahead, the works on github are free but you don't give credits to the creator.
Thanks for your request, let's see how we can solve it

**Comment by jbleyel** [comment]
What's your native language?

**Comment by jbleyel** [comment]
What you mean with "don't give credits to the creator" .. i'm the creator of these changes -> https://github.com/jbleyel/mmPicons/commit/14da4ba8d4c218f23ad56148032877637f6458aa

**Comment by Belfagor2005** [comment]
and work ?

**Comment by Belfagor2005** [comment]
i have updated, but not work on my box (dinobot 4kmini + atv 6.5 image)
thank's

**Comment by Belfagor2005** [comment]
not work on my box (dinobot 4kmini + atv 6.5 image)

> 
> 
> What's your native language?

Italy

**Comment by jbleyel** [comment]
I have only fixed the black picons. You need to copy my changes to the other parts.
That's why i give you the hints.

**Comment by jbleyel** [comment]
You also need to check the comment on the checkMyFile function.

**Comment by Belfagor2005** [comment]
I do not find the changes made in the class black picons
Thanks for the suggestions, I gladly accept them

**Comment by jbleyel** [comment]
I have changed the function checkMyFile and uncomment the install.
Check this ->  https://github.com/jbleyel/mmPicons/commit/14da4ba8d4c218f23ad56148032877637f6458aa

**Comment by jbleyel** [comment]
I can make a review.
Give me a ping if you have finished your changes.

**Comment by Belfagor2005** [comment]
the problem with Py3 is 
Starting factory <HTTPProgressDownloader: b'https://www.mediafire.com/file/mmyfile/mmk_Lost_417x250_trs.zip/file'>
download error = [Failure instance: Traceback (failure with no frames): <class 'twisted.web.error.Error'>: 400 Bad Request

I hope for a fix on ATV 6.5 soon
Yes, I change and update

**Comment by jbleyel** [comment]
Sorry .. you need to get this file -> https://github.com/openatv/enigma2/commit/3974e84a59be2a8eb4d2250a876713d38e8f56b4


Or change the file on the box.

**Comment by Belfagor2005** [comment]
yessssssssssss

ok now

**Comment by jbleyel** [comment]
You are finished yet so i can do the review?

**Comment by Belfagor2005** [comment]
yes

**Comment by jbleyel** [comment]
I'm done see my pull request
